export const SET_NEW_MESSAGE = 'SET_NEW_MESSAGE';
export const RECEIVE_BOT_RESPONSE = 'RECEIVE_BOT_RESPONSE';
export const UPDATE_ID = 'UPDATE_ID';
export const SET_LOADING = 'SET_LOADING';
export const UPDATE_ARTICLES = 'UPDATE_ARTICLES';
export const UPDATE_ALL_KNOWLEDGE = 'UPDATE_ALL_KNOWLEDGE';
export const UPDATE_QUERY = 'UPDATE_QUERY';